name: tregs
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.8.30=hf0a4a13_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.8=py312hd8f9ff3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.29.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h237132a_0
  - libcxx=19.1.3=ha82da77_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.2=h3422bc3_5
  - libmpdec=4.0.0=h99b78c6_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.47.0=hbaaea75_1
  - libzlib=1.3.1=h8359307_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.5=h7bae524_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.2=h8359307_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py312h0bf5046_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.0=h47c9636_0_cpython
  - python_abi=3.12=5_cp312
  - pyzmq=26.2.0=py312hf8a1cbd_3
  - readline=8.2=h92ec313_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4.1=py312h024a12e_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.5=h9f5b81c_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - pip:
      - biopython==1.84
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.54.1
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - matplotlib==3.9.2
      - numba==0.60.0
      - numpy==2.0.2
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - seaborn==0.13.2
      - stack-data==0.6.3
      - -e ./.
      - tzdata==2024.2
